### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by juanparadox** [juanparadox/react-tachyons#4]
Since the styling is based off tachyons, should this library only use the tachyon colors, or should we make our own? The user would still be able to customize the library based off the way tachyons works currently. But as a baseline, should we have our own additional colors that we use for examples and overall design?

**Comment by anater** [comment]
I like having the ability to use plain text ('red', 'yellow') that leverages tachyons colors (or the user-customized ones) if they exist and then CSS otherwise. So some switch statement that runs through the colors in tachyons and if that doesn't work, add an inline-style (or create a class?) with the value passed. That way the user could pass hex, rgb, hsl, or any future format that CSS will accept.
